#!/usr/bin/python3

import sys, socket, select

seqNum = 0
topoview = []

# check arguments
if (len(sys.argv) != 4):
    print("Usage: virtualrouter <nfe-ip> <nfe-port> <virtual-router-id> ")
    sys.exit(0)

if (not sys.argv[2].isnumeric() or not sys.argv[3].isnumeric()):
    print("<nfe-port> or <virtual-router-id> must be a number ")
    sys.exit(0)

#extract info from args
serverName = sys.argv[1]
serverPort = int(sys.argv[2])
routerId = int(sys.argv[3])

# make new socket
addr = (serverName, serverPort)
try:
    nfeSocket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
except socket.error:
    print("Cannot create socket. ")
    sys.exit(1)

#prepare and send init
tosend = (1).to_bytes(4, byteorder='big') 
tosend += routerId.to_bytes(4, byteorder='big')
nfeSocket.sendto(tosend, addr)

while 1:
    readlist = [nfeSocket]
    readable, _, exc = select.select(readlist,[],[])

    for r in readable:
        data, addr = r.recvfrom(4096)
        print(data)
        packettype = int.from_bytes(data[0:4], byteorder='big')
        print(packettype)
        if (packettype == 3): #LSA
            outstring = "RECEIVED:"
            sendID = int.from_bytes(data[4:8], byteorder='big')
            outstring += "SID(" + str(sendID) +"),"
            destID = int.from_bytes(data[8:12], byteorder='big')
            outstring += "DID("+str(destID)+"),"
            advID = int.from_bytes(data[12:16], byteorder='big')
            outstring += "AID("+str(advID)+"),"
            seq = int.from_bytes(data[16:20], byteorder='big')
            outstring += "SEQ("+str(seq)+")"
            numLink = int.from_bytes(data[20:24], byteorder='big')
            for i in range(numLink):
                nID = int.from_bytes(data[24+i*8:28+i*8], byteorder='big')
                cost = int.from_bytes(data[28+i*8:32+i*8], byteorder='big')
                outstring += ",NID("+str(nID)+"),LC(?)"
                link = ((advID,nID),cost)
                topoview.append(link)
            print(outstring)
        elif (packettype == 4): #init-reply
            outstring = "RECEIVED:"
            print("init reply detected")
            numLink = data[4:8]
            print("Received numlink")
            numLink = int.from_bytes(numLink, byteorder='big')
            print(numLink)
            for i in range(numLink):
                nID = int.from_bytes(data[8+i*8:12+i*8], byteorder='big')
                cost = int.from_bytes(data[12+i*8:16+i*8], byteorder='big')
                print("Received nID and cost")
                outstring += ",NID("+str(nID)+"),LC("+str(cost)+")"
                link = ((routerId,nID),cost)
                topoview.append(link)
                print(link)
            print(outstring)
        elif (packettype == 5):
            print(topoview)
            sys.exit(0)





